id: P006723
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22273
  title: གསུང་འབུམ། ཙོང་ཁ་པ།（བླ་བྲང་པར་མ།）
  author: ''
  volumes:
    7376015cea654b4e94fc615fef9e94c6:
      image_group_id: I1KG2236
      title: ''
      volume_number: 1
      total_pages: 952
      base_file: v001.txt
    7ed007a6b74345dcaf3cc34d1ad637f6:
      image_group_id: I1KG2237
      title: ''
      volume_number: 2
      total_pages: 872
      base_file: v002.txt
    8b51e73336224b9abd081272a2367033:
      image_group_id: I1KG2238
      title: ''
      volume_number: 3
      total_pages: 873
      base_file: v003.txt
    f2c0c19428c74639a0edd14ab40f1d9b:
      image_group_id: I1KG2239
      title: ''
      volume_number: 4
      total_pages: 1088
      base_file: v004.txt
    01119b51a21149d5a421c634ebffecf3:
      image_group_id: I1KG2240
      title: ''
      volume_number: 5
      total_pages: 1094
      base_file: v005.txt
    f07e5a7461834df4b989492ca01801d6:
      image_group_id: I1KG2241
      title: ''
      volume_number: 6
      total_pages: 624
      base_file: v006.txt
    028d65a7e9a646be861cfe2bc55bc4ac:
      image_group_id: I1KG2242
      title: ''
      volume_number: 7
      total_pages: 775
      base_file: v007.txt
    622d113511884e459637450813c99b00:
      image_group_id: I1KG2243
      title: ''
      volume_number: 8
      total_pages: 984
      base_file: v008.txt
    515fac530eb646fc81f697f3d360ae4d:
      image_group_id: I1KG2244
      title: ''
      volume_number: 9
      total_pages: 730
      base_file: v009.txt
    a5e6c283ac064ebc9440a99a7f2d7b7d:
      image_group_id: I1KG2245
      title: ''
      volume_number: 10
      total_pages: 678
      base_file: v010.txt
    da107f494d064415bb64d462c8240b44:
      image_group_id: I1KG2246
      title: ''
      volume_number: 11
      total_pages: 834
      base_file: v011.txt
    0768a9b1b6604715b2b71258bd8928c4:
      image_group_id: I1KG2247
      title: ''
      volume_number: 12
      total_pages: 630
      base_file: v012.txt
    e1904d40e76041ed9df0aeb72ed9d5c7:
      image_group_id: I1KG2248
      title: ''
      volume_number: 13
      total_pages: 1026
      base_file: v013.txt
    dedf89b2eeec44ffb393d78b65bf344b:
      image_group_id: I1KG2249
      title: ''
      volume_number: 14
      total_pages: 1008
      base_file: v014.txt
    bbfb16c78ed5422fb1686a36e9333308:
      image_group_id: I1KG2250
      title: ''
      volume_number: 15
      total_pages: 836
      base_file: v015.txt
    a0213d148f084a14986ac5871f624752:
      image_group_id: I1KG2251
      title: ''
      volume_number: 16
      total_pages: 990
      base_file: v016.txt
    d84c92b59ce9496ca6c8b31342882eb4:
      image_group_id: I1KG2252
      title: ''
      volume_number: 17
      total_pages: 960
      base_file: v017.txt
    e10d39be28e24d17a91f8f3e22c927eb:
      image_group_id: I1KG2253
      title: ''
      volume_number: 18
      total_pages: 952
      base_file: v018.txt
