id: I56BF8105
legacy_id: P006723
ocr_import_info:
  bdrc_scan_id: W22273
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T03:30:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:07:32.287987+00:00'
last_modified: 2022-09-02 05:13:43.415743
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22273
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22273
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཙོང་ཁ་པ།（བླ་བྲང་པར་མ།）
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6671942753081492
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I1KG2253:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2253
      total_pages: 952
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I1KG2253.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6798691866312956
    legacy_id: v018
  I1KG2238:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2238
      total_pages: 873
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG2238.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6588300612782573
    legacy_id: v003
  I1KG2247:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2247
      total_pages: 630
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG2247.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6375012602810756
    legacy_id: v012
  I1KG2248:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2248
      total_pages: 1026
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG2248.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5702956627892816
    legacy_id: v013
  I1KG2236:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2236
      total_pages: 952
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2236.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6819447208709073
    legacy_id: v001
  I1KG2240:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2240
      total_pages: 1094
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG2240.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.694893943406694
    legacy_id: v005
  I1KG2244:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2244
      total_pages: 730
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG2244.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6183248491911415
    legacy_id: v009
  I1KG2237:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2237
      total_pages: 872
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG2237.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6638206376373964
    legacy_id: v002
  I1KG2245:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2245
      total_pages: 678
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG2245.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6652819638230227
    legacy_id: v010
  I1KG2243:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2243
      total_pages: 984
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG2243.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.691349735142218
    legacy_id: v008
  I1KG2241:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2241
      total_pages: 624
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG2241.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6984632663810435
    legacy_id: v006
  I1KG2246:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2246
      total_pages: 834
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG2246.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.709062901324962
    legacy_id: v011
  I1KG2250:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2250
      total_pages: 836
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I1KG2250.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6409735262956615
    legacy_id: v015
  I1KG2242:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2242
      total_pages: 775
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG2242.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7060226837703225
    legacy_id: v007
  I1KG2251:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2251
      total_pages: 990
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I1KG2251.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7099502296347036
    legacy_id: v016
  I1KG2249:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2249
      total_pages: 1008
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1KG2249.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6823779816789618
    legacy_id: v014
  I1KG2239:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2239
      total_pages: 1088
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG2239.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6680303442934082
    legacy_id: v004
  I1KG2252:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2252
      total_pages: 960
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I1KG2252.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.604436420996168
    legacy_id: v017
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
