id: I56BF8105
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:36:39+00:00'
last_modified: '2022-06-08T06:24:07.447064+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22273
  title: གསུང་འབུམ། ཙོང་ཁ་པ།（བླ་བྲང་པར་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E12D:
      image_group_id: I1KG2236
      title: ''
      total_pages: 952
      order: 1
      base_file: E12D.txt
    A30E:
      image_group_id: I1KG2237
      title: ''
      total_pages: 872
      order: 2
      base_file: A30E.txt
    '8941':
      image_group_id: I1KG2238
      title: ''
      total_pages: 873
      order: 3
      base_file: 8941.txt
    71FE:
      image_group_id: I1KG2239
      title: ''
      total_pages: 1088
      order: 4
      base_file: 71FE.txt
    A055:
      image_group_id: I1KG2240
      title: ''
      total_pages: 1094
      order: 5
      base_file: A055.txt
    8FAD:
      image_group_id: I1KG2241
      title: ''
      total_pages: 624
      order: 6
      base_file: 8FAD.txt
    '9615':
      image_group_id: I1KG2242
      title: ''
      total_pages: 775
      order: 7
      base_file: 9615.txt
    CEEC:
      image_group_id: I1KG2243
      title: ''
      total_pages: 984
      order: 8
      base_file: CEEC.txt
    '4060':
      image_group_id: I1KG2244
      title: ''
      total_pages: 730
      order: 9
      base_file: 4060.txt
    FBCB:
      image_group_id: I1KG2245
      title: ''
      total_pages: 678
      order: 10
      base_file: FBCB.txt
    E79D:
      image_group_id: I1KG2246
      title: ''
      total_pages: 834
      order: 11
      base_file: E79D.txt
    689D:
      image_group_id: I1KG2247
      title: ''
      total_pages: 630
      order: 12
      base_file: 689D.txt
    '5297':
      image_group_id: I1KG2248
      title: ''
      total_pages: 1026
      order: 13
      base_file: 5297.txt
    9EBA:
      image_group_id: I1KG2249
      title: ''
      total_pages: 1008
      order: 14
      base_file: 9EBA.txt
    01C9:
      image_group_id: I1KG2250
      title: ''
      total_pages: 836
      order: 15
      base_file: 01C9.txt
    C89A:
      image_group_id: I1KG2251
      title: ''
      total_pages: 990
      order: 16
      base_file: C89A.txt
    4F04:
      image_group_id: I1KG2252
      title: ''
      total_pages: 960
      order: 17
      base_file: 4F04.txt
    E906:
      image_group_id: I1KG2253
      title: ''
      total_pages: 952
      order: 18
      base_file: E906.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
